### ISSUE TITLE
deep motion editing中的retarget的泛化行很差？

### ISSUE THREAD

**Issue by wuxiaolianggit** [crissallan/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting#2]
我用新的角色，骨骼点和层级结构是一样的，只是比例不一样的，进行动作转移的时候，就一塌糊涂，您知道怎么解决吗 @crissallan

**Comment by ANYMS-A** [comment]
> 我用新的角色，骨骼点和层级结构是一样的，只是比例不一样的，进行动作转移的时候，就一塌糊涂，您知道怎么解决吗 @crissallan

首先你可能要确定下，你的角色的T-pose（人物初始的朝向，姿势）是否和训练数据的T-pose一样。
如果在T-pose相同的前提下，比例相近的话，应该不会出现太离谱的错误吧，我这么认为。

**Comment by wuxiaolianggit** [comment]
我的应用场景角色的T-pose是差不多的，但是比例可能会差别比较大，例如肩膀的宽度有的很大有的很小，但是在做一个合并两只手的动作时，肩膀窄的就可以合并收，肩膀宽的就完全做不到，您有办法可以解决吗？ @crissallan

**Comment by ANYMS-A** [comment]
> 我的应用场景角色的T-pose是差不多的，但是比例可能会差别比较大，例如肩膀的宽度有的很大有的很小，但是在做一个合并两只手的动作时，肩膀窄的就可以合并收，肩膀宽的就完全做不到，您有办法可以解决吗？ @crissallan

这个估计是有难度的，因为手合并这个动作，一定程度上不完全取决于骨架的信息，是不是还取决于模型的mesh点的位置，但是我们训练的时候，是完全没有考虑模型的mesh信息的。

**Comment by wuxiaolianggit** [comment]
我的理解是，目前这个算法只考虑到学习到模型的旋转向量，没有考虑到模型之间的相对位移，是这样吗 @crissallan

**Comment by ANYMS-A** [comment]
> 我的理解是，目前这个算法只考虑到学习到模型的旋转向量，没有考虑到模型之间的相对位移，是这样吗 @crissallan

我没太理解你所说的 “模型之间的相对位移” 这个概念。 由于BVH文件的特性，在T-pose相似的前提下，人物的运动取决于root joint的位移，旋转，以及剩下所有关节的旋转，因此，只要我们估计出了root joint的位移，以及所有关节的旋转，就可以重建出这个骨骼动画。

如果你所说的相对位移，指的是模型的各个关节经旋转后在3D空间中的位置。那么，我们是可以根据root joint的位移，以及所有的关节旋转，经由Forward Kinematics算法，推导出各个关节所在的位置的。原作者也有把这个由FK计算出的位置，作为一个loss，来进行优化的。

**Comment by wuxiaolianggit** [comment]
首先向您说声对不起，我打错字了，我的相对位移就是模型各个关节旋转后的相对位置，例如手部合并的相对位移是0，迁移到另外一个角色模型上，不管肩膀宽度是多少，手部的相对位移应该也是0，这是我要表达的意思。 @crissallan

**Comment by wuxiaolianggit** [comment]
请问一下大神，如果模型中一个骨骼点的位移发生改变，其他相关骨骼点也会相应改变位移和旋转向量，您有了解这方面的算法吗？ @crissallan

**Comment by ANYMS-A** [comment]
> 请问一下大神，如果模型中一个骨骼点的位移发生改变，其他相关骨骼点也会相应改变位移和旋转向量，您有了解这方面的算法吗？ @crissallan

这个确实不太清楚，不过你可以先了解下 Inverse Kinematic。我感觉这个或许能解决你的问题

**Comment by wuxiaolianggit** [comment]
好的，我了解一下，多谢您的回复啊

**Comment by ANYMS-A** [comment]
> 好的，我了解一下，多谢您的回复啊

没事没事，互相学习交流而已
