### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/Mixamo/Aj/Aj.bvh'

### ISSUE THREAD

**Issue by zq1335030905** [crissallan/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting#3]
hello. Here is an error when I run "python inference.py". Is the dataset lack of some bvh data? and how can I solve this problem. Thanks so much.

**Comment by ANYMS-A** [comment]
> hello. Here is an error when I run "python inference.py". Is the dataset lack of some bvh data? and how can I solve this problem. Thanks so much.

Yes you need to download the bvh files of character Aj and BigVegas from the Mixamo database. Follow the tutourial from this link: https://forums.unrealengine.com/community/community-content-tools-and-tutorials/1376068-script-mixamo-download-script

Then you can download a lot of fbx files from the Mixamo dataset automatically. After that, install Blender for your computer and use the python script in ./datasets/fbx2bvh.py to convert the fbx files to bvh files.

Hope this would help!

**Comment by zq1335030905** [comment]
thank you so much. Your reply is very useful for me.



At 2020-08-11 16:47:09, "crissallan" <notifications@github.com> wrote:

hello. Here is an error when I run "python inference.py". Is the dataset lack of some bvh data? and how can I solve this problem. Thanks so much.

Yes you need to download the bvh files of character Aj and BigVegas from the Mixamo database. Follow the tutourial from this link: https://forums.unrealengine.com/community/community-content-tools-and-tutorials/1376068-script-mixamo-download-script

Then you can download a lot of fbx files from the Mixamo dataset automatically. After that, install Blender for your computer and use the python script in ./datasets/fbx2bvh.py to convert the fbx files to bvh files.

Hope this would help!
