### ISSUE TITLE
关于paired数据的疑问

### ISSUE THREAD

**Issue by Vincent-2017** [crissallan/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting#4]
你好，我看你的复现里训练每次输入paired数据 dynamic_a, dynamic_b，我想问下他们之间具体有什么关系吗？
还有损失rec_loss_1与rec_loss_4里都有表示旋转的denorm_rot_b和dynamic_b，是否是重复计算？

**Comment by ANYMS-A** [comment]
dynamic数据就是bvh文件里读取的关节的旋转数据。原论文是用的unpaired的数据，你也可以理解为非监督学习的方式，也就是说训练时，输入的人物a的数据是一个扔棒球的动作，不需要人物b的同样的扔棒球动作所为target来计算loss。但是我复现不出来这种unpaired的训练方式（后面发现很可能是我的实验里没有ee loss这一项）。所以我用的是paired的数据。

**Comment by ANYMS-A** [comment]
rec_loss1和4还是有不一样的，denorm表示的是de-normalize。我记得我之前实验的时候，如果去掉rec_loss4，最后retarget的效果不是很好。不过我貌似没有试过去掉rec_loss1只保留rec_loss4会怎么样，有兴趣的话可以试试😄

**Comment by Vincent-2017** [comment]
好的，多谢解答，实际上就是denorm_rot_b和dynamic_b之间会有变换关系是吧，比如会引入mean和var变量，了解了。
